# Welcome to Jekyll!

title:                  "Appix Jekyll Template"
email:                  "themeix@gmail.com"
description:            "Themeix is a awesome company for selling jekyll,ghost,html, blogging and wordpress websites."

baseurl:                "https://www.tuxwp.com"
url:                    "https://www.tuxwp.com"

# Build settings
markdown:               kramdown
theme:                  minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate:               6
permalink:              pretty

mailchimp_link:         "//themeix.us16.list-manage.com/subscribe?u=4b7aa1c5c5ac54be844d58bcb&id=0e85c09412"

# social links

twitter_username:       "gopalraha"
facebook_username:      "themeix"
google_plus_username:   "themeix"
instragram_username:    "themeix"
linkedin_username:      "themeix"
pinterest_username:     "themeix"
dribble_username:       "themeix"
github_username:        "themeix"
